services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: batlahouse
      DB_PASSWORD: wandervibez
      DB_NAME: smartpg
    depends_on:
      - db
  
  db:
    image: postgres:17.5
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"