services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      - db
    networks:
      - smartnet
  
  db:
    image: postgres:17.5
    ports:
      - "5433:5432"
    command: ["postgres" ,"-c" , "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      - smartnet
  
  pgbouncer:
    build: ./pgbouncer
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    depends_on:
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

networks:
  smartnet:
    driver: bridge